name: publish

on:
  push:
    branches: main

permissions:
  contents: write # push the changesets release branch and publish tags
  pull-requests: write # create and update the release PR
  id-token: write # npm Trusted Publishing (OIDC) + provenance

jobs:
  publish:
    if: ${{ github.repository != 'nl-design-system/example' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Install pnpm package manager
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

      - name: Set up Node.js version and cache
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Publish to the npm Registry
        uses: changesets/action@e0145edc7d9d8679003495b11f87bd8ef63c0cba # v1.5.3
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
          GIT_AUTHOR_NAME: "NL Design System"
          GIT_COMMITTER_EMAIL: ${{ secrets.GIT_COMMITTER_EMAIL }}
          GIT_COMMITTER_NAME: "NL Design System"
        with:
          commit: "docs(release): design system packages"
          setupGitUser: false
          title: "docs(release): design system packages"
          publish: "pnpm run changeset:publish"
